### ISSUE TITLE
Unable to connect db in IE 11 browser

### ISSUE THREAD

**Issue by sadashivm** [sql-js/sql.js#239]
Hello,
I'm getting console error in IE 11 browser. please find the attached screenshot.

![error1](https://user-images.githubusercontent.com/10355473/40294655-25ea78be-5cf4-11e8-9100-1513df5f0f15.JPG)
![error2](https://user-images.githubusercontent.com/10355473/40294656-26b89672-5cf4-11e8-98f1-5a5ec6257733.JPG)

Below console error showing in sql.js file

abort("Assertion failed: this is a legacy browser, build with LEGACY_VM_SUPPORT") at Error: 0
   at jsStackTrace (http://127.0.0.1:8081/js/sql.js:3:13747)
   at stackTrace (http://127.0.0.1:8081/js/sql.js:3:13882)
   at abort (http://127.0.0.1:8081/js/sql.js:20:8436)
   at assert (http://127.0.0.1:8081/js/sql.js:3:6512)
   at Anonymous function (http://127.0.0.1:8081/js/sql.js:3:17850)
   at Global code (http://127.0.0.1:8081/js/sql.js:2:1)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by mcfly3001** [comment]
Hi, I have the same issue when testing my site on IE 11. Is there a workaround, solution available?

**Comment by object71** [comment]
Hi, can this also work on IE?

**Comment by Thetiso** [comment]
sad to know it's not  feasible on IE.

**Comment by aaaristo** [comment]
Would this work with wasm2js?

**Comment by aaaristo** [comment]
works adding -s LEGACY_VM_SUPPORT=1 to dist/sql-asm-debug.js

**Comment by yanli0303** [comment]
@aaaristo Awesome, I built the `sql-asm.js` with both `-s LEGACY_VM_SUPPORT=1` and `-s ALLOW_MEMORY_GROWTH=1` and it works nicely in IE 11 32bit.

```diff
diff --git a/Makefile b/Makefile
index 14e0e71..17efa3d 100644
--- a/Makefile
+++ b/Makefile
@@ -39,6 +39,8 @@ EMFLAGS = \
 
 EMFLAGS_ASM = \
        -s WASM=0
+       -s LEGACY_VM_SUPPORT=1
+       -s ALLOW_MEMORY_GROWTH=1
 
 EMFLAGS_ASM_MEMORY_GROWTH = \
        -s WASM=0 \
```

**Comment by kaizhu256** [comment]
can we simplify the distribution by merging `sql-asm-memory-growth.js` into `sql-asm.js`?

i think the only reason for `asm.js` these days is legacy-support where performance doesn't matter.

**Comment by lovasoa** [comment]
Yes, I agree.

> @aaaristo Awesome, I built the [`sql-asm.js`](https://github.com/yanli0303/sql-js-worker-test/tree/master/docs/static) with both `-s LEGACY_VM_SUPPORT=1` and `-s ALLOW_MEMORY_GROWTH=1` and it works nicely in IE 11 32bit.
> 
> ```diff
> diff --git a/Makefile b/Makefile
> index 14e0e71..17efa3d 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -39,6 +39,8 @@ EMFLAGS = \
>  
>  EMFLAGS_ASM = \
>         -s WASM=0
> +       -s LEGACY_VM_SUPPORT=1
> +       -s ALLOW_MEMORY_GROWTH=1
>  
>  EMFLAGS_ASM_MEMORY_GROWTH = \
>         -s WASM=0 \
> ```

We can merge that and remove asm-memory-growth.
