### ISSUE TITLE
Ionic-Angular 6 Error: both async and sync fetching of the wasm failed

### ISSUE THREAD

**Issue by Romulogss** [sql-js/sql.js#499]
Hello, I'm trying to use sql.js with typeorm in an ionic@6 application, but the following error happens:
```
zone.js:1523          GET http://localhost:8100/sql-wasm.wasm 404 (Not Found)
Error: both async and sync fetching of the wasm failed
    at Object.Module.onAbort (sql-wasm.js:40:20)
    at I (sql-wasm.js:104:97)
    at lb (sql-wasm.js:105:136)
    at sql-wasm.js:105:408
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (core.mjs:25488:1)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
```

My custom webpack:

```
const webpack = require('webpack');
console.log('The custom config is used');
module.exports = {
  plugins: [
    new webpack.ProvidePlugin({
      'window.SQL': 'sql.js/dist/sql-wasm.js'
    }),
    new webpack.NormalModuleReplacementPlugin(/typeorm$/, function (result) {
      result.request = result.request.replace(/typeorm/, "typeorm/browser");
    })
  ],

  resolve: {
    fallback: {
      fs: false,
      net: false,
      tls: false
    }
  }
};
```
My Ionic Info: 
```
Ionic:

   Ionic CLI                     : 6.18.1 
   Ionic Framework               : @ionic/angular 6.0.5
   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.15.0 
   npm    : 6.14.8
   OS     : Windows 10

```
I'm using sql.js@1.3.2 typeorm@0.2.41

Would anyone have a solution?

**Comment by danbarretto** [comment]
Did you manage to solve this? I'm facing the same problem.
