### ISSUE TITLE
Containerized Development Environment setup fails on apt-get not finding libappindicator3-1

### ISSUE THREAD

**Issue by gthb** [sql-js/sql.js#510]
Following the recommended path in https://github.com/sql-js/sql.js/blob/master/CONTRIBUTING.md, the “Reopen in container” step fails as apt-get does not find the package `libappindicator3-1`:

```
 => ERROR [8/9] RUN apt-get update      && apt-get install -y         ca-  4.6s
------                                                                          
 > [8/9] RUN apt-get update      && apt-get install -y         ca-certificates         fonts-liberation         libappindicator3-1         libasound2         libatk-bridge2.0-0         libatk1.0-0         libc6         libcairo2         libcups2         libdbus-1-3         libexpat1         libfontconfig1         libgbm1         libgcc1         libglib2.0-0         libgtk-3-0         libnspr4         libnss3         libpango-1.0-0         libpangocairo-1.0-0         libstdc++6         libx11-6         libx11-xcb1         libxcb1         libxcomposite1         libxcursor1         libxdamage1         libxext6         libxfixes3         libxi6         libxrandr2         libxrender1         libxss1         libxtst6         lsb-release         wget         xdg-utils:
#11 0.560 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]        
#11 0.560 Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#11 0.666 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#11 0.676 Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
#11 0.819 Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [148 kB]
#11 0.968 Get:6 http://deb.debian.org/debian bullseye/contrib amd64 Packages [50.5 kB]
#11 1.017 Get:7 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
#11 1.164 Get:8 https://dl.yarnpkg.com/debian stable/main all Packages [10.9 kB]
#11 1.262 Get:9 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.9 kB]
#11 1.880 Get:10 http://deb.debian.org/debian bullseye/non-free amd64 Packages [93.8 kB]
#11 1.921 Get:11 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
#11 3.009 Fetched 8715 kB in 3s (3405 kB/s)
#11 3.009 Reading package lists...
#11 3.614 Reading package lists...
#11 4.236 Building dependency tree...
#11 4.419 Reading state information...
#11 4.464 Package libappindicator3-1 is not available, but is referred to by another package.
#11 4.464 This may mean that the package is missing, has been obsoleted, or
#11 4.464 is only available from another source
#11 4.464 
#11 4.573 E: Package 'libappindicator3-1' has no installation candidate
------
executor failed running [/bin/sh -c apt-get update      && apt-get install -y         ca-certificates         fonts-liberation         libappindicator3-1         libasound2         libatk-bridge2.0-0         libatk1.0-0         libc6         libcairo2         libcups2         libdbus-1-3         libexpat1         libfontconfig1         libgbm1         libgcc1         libglib2.0-0         libgtk-3-0         libnspr4         libnss3         libpango-1.0-0         libpangocairo-1.0-0         libstdc++6         libx11-6         libx11-xcb1         libxcb1         libxcomposite1         libxcursor1         libxdamage1         libxext6         libxfixes3         libxi6         libxrandr2         libxrender1         libxss1         libxtst6         lsb-release         wget         xdg-utils]: exit code: 100
[6400 ms] Error: Command failed: docker build -f /Users/gthb/git/sql.js/.devcontainer/Dockerfile -t vsc-sql.js-0fac5b64e27214e15d16e257897b9407 --build-arg VARIANT=14 /Users/gthb/git/sql.js/.devcontainer
[6401 ms]     at Tu (/Users/gthb/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:3219)
[6401 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[6401 ms]     at async LR (/Users/gthb/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:1567)
[6401 ms]     at async zy (/Users/gthb/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:594)
[6401 ms]     at async $R (/Users/gthb/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:2007)
[6401 ms]     at async Zy (/Users/gthb/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:3112)
[6401 ms]     at async BR (/Users/gthb/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12448)
[6401 ms]     at async qR (/Users/gthb/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12204)
[6407 ms] Exit code 1
[6409 ms] Command failed: /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/gthb/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/gthb/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/gthb/git/sql.js --workspace-mount-consistency cached --id-label vsch.local.folder=/Users/gthb/git/sql.js --id-label vsch.quality=stable --log-level debug --log-format json --config /Users/gthb/git/sql.js/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[6409 ms] Exit code 1
```

Runtime context:
* macOS 10.15.7 (Intel chip)
* Visual Studio Code 1.67.2
* Docker Desktop 4.8.2 (79419)
* Docker Engine v20.10.14.

**Comment by rhashimoto** [comment]
The docker build works for me. Your log shows that you're using the bullseye (Debian 11) repo, while the [Dockerfile specifies buster](https://github.com/sql-js/sql.js/blob/7017d56b611177fca722f056d97b99db873abc99/.devcontainer/Dockerfile#L9) (Debian 10). Did you perhaps make a config change to use the latest Debian? If so, you can't count on the dependencies to be exactly the same. If not, your docker toolchain is apparently fetching the wrong image.

**Comment by gthb** [comment]
Nope, I made no changes — just followed the instructions, and my docker toolchain is just a vanilla install of Docker Desktop, I've not done anything else with it.

I think that Dockerfile line just declaring an argument with a _default value_ of `14-buster` that's then _overridden_ to be `14` by [the build argument in `devcontainer.json`](https://github.com/sql-js/sql.js/blob/7017d56b611177fca722f056d97b99db873abc99/.devcontainer/devcontainer.json#L8-L10)?
```json
		"args": {
			"VARIANT": "14"
		},
```
... and the `14` variant then resolves to whatever is the default Node.js 14 image _at the time the docker toolchain fetches the base image_ — and that default was buster when your docker toolchain fetched the base image, so that's why you don't observe the problem locally, but the default changed to bullseye recently: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/typescript-node/history/0.204.0.md#variant-16-bullseye

Yep, that seems to be it. When I [change that arg to `14-buster` in `devcontainer.json`](https://github.com/sql-js/sql.js/pull/511), the “Reopen in container” step completes without problems, and the build and test tasks run just fine for me.
