### ISSUE TITLE
Can't build sql.js: Module not found error

### ISSUE THREAD

**Issue by johncardiologs** [sql-js/sql.js#526]
I'm following the instructions on [Contributing.md](https://github.com/sql-js/sql.js/blob/master/CONTRIBUTING.md).

I manage to "Reopen in container" and `npm install` but `npm test` fails:

```
Setting environment variables:
PATH = /emsdk:/emsdk/upstream/emscripten:/emsdk/node/14.18.2_64bit/bin:/vscode/vscode-server/bin/linux-x64/3b889b090b5ad5793f524b5d1d39fda662b96a2a/bin/remote-cli:/usr/local/share/npm-global/bin:/usr/local/share/nvm/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.local/bin
Clearing existing environment variable: EM_NODE_JS
node ➜ /workspaces/sql.js (master ✗) $ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
audited 294 packages in 1.11s

67 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New major version of npm available! 6.14.15 → 8.17.0      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v8.17.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

node ➜ /workspaces/sql.js (master ✗) $ npm test

> sql.js@1.7.0 test /workspaces/sql.js
> npm run lint && npm run test-asm && npm run test-asm-debug && npm run test-wasm && npm run test-wasm-debug && npm run test-asm-memory-growth


> sql.js@1.7.0 lint /workspaces/sql.js
> eslint .


> sql.js@1.7.0 test-asm /workspaces/sql.js
> node --unhandled-rejections=strict test/all.js asm

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../dist/sql-asm.js'
Require stack:
- /workspaces/sql.js/test/load_sql_lib.js
- /workspaces/sql.js/test/all.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at module.exports (/workspaces/sql.js/test/load_sql_lib.js:5:21)
    at Object.<anonymous> (/workspaces/sql.js/test/all.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/sql.js/test/load_sql_lib.js',
    '/workspaces/sql.js/test/all.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sql.js@1.7.0 test-asm: `node --unhandled-rejections=strict test/all.js asm`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sql.js@1.7.0 test-asm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-08-17T20_29_14_979Z-debug.log
npm ERR! Test failed.  See above for more details.
```

My end goal is to recompile with the rtree flags.

**Comment by johncardiologs** [comment]
haha I didn't run `npm rebuild` first... :woman_facepalming: thanks anyway!
